# Generated by Django 4.1.6 on 2023-02-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LineSheet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "time_tag",
                    models.TextField(blank=True, verbose_name="Отметка времени"),
                ),
                (
                    "school",
                    models.TextField(
                        blank=True, verbose_name="Образовательная площадка"
                    ),
                ),
                (
                    "teacher",
                    models.TextField(
                        blank=True,
                        verbose_name="Ф.И.О. учителя/воспитателя (ПОЛНОСТЬЮ) *",
                    ),
                ),
                (
                    "event",
                    models.TextField(
                        blank=True,
                        verbose_name="Название мероприятия (в родительном падеже).  О посещении ....",
                    ),
                ),
                (
                    "date_departure",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="Дата выезда"
                    ),
                ),
                (
                    "time_departure",
                    models.TimeField(
                        blank=True, default=None, null=True, verbose_name="Время выезда"
                    ),
                ),
                (
                    "date_arrival",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="Дата приезда"
                    ),
                ),
                (
                    "time_arrival",
                    models.TimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Время приезда обратно",
                    ),
                ),
                (
                    "transport",
                    models.TextField(
                        blank=True,
                        verbose_name="На каком виде транспорта Вы будете добираться до места проведения мероприятия",
                    ),
                ),
                (
                    "adress",
                    models.TextField(
                        blank=True, verbose_name="Адрес проведения мероприятия "
                    ),
                ),
                (
                    "route",
                    models.TextField(
                        blank=True,
                        verbose_name="Опишите маршрут движения (как и на чем будете добираться до места)",
                    ),
                ),
                (
                    "students",
                    models.TextField(
                        blank=True,
                        verbose_name="№, Ф.И.О. обучающихся, дата рождения, класс, ФИО и № телефона одного из родителей/законного представителя)",
                    ),
                ),
                (
                    "companion",
                    models.TextField(
                        blank=True,
                        verbose_name="Сопровождающие (полностью Ф.И.О) ВНИМАНИЕ!!! Сопровождающими могут быть ТОЛЬКО сотрудники комплекса",
                    ),
                ),
                (
                    "plan",
                    models.TextField(
                        blank=True,
                        verbose_name="Укажите план мероприятия (согласно пунктам)",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                (
                    "number",
                    models.TextField(
                        blank=True, verbose_name="Номер телефона для контакта"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
