# Generated by Django 4.1.6 on 2023-02-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tg_id', models.IntegerField(unique=True)),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('allow_user', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='linesheet',
            name='email',
            field=models.TextField(blank=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='linesheet',
            name='event',
            field=models.TextField(blank=True, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='linesheet',
            name='teacher',
            field=models.TextField(blank=True, verbose_name='Ф.И.О. учителя/воспитателя'),
        ),
    ]
