# Generated by Django 4.1.6 on 2023-05-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_user_alter_linesheet_email_alter_linesheet_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linesheet",
            name="class_tag",
            field=models.TextField(blank=True, verbose_name="Номер и литера класса"),
        ),
        migrations.AddField(
            model_name="linesheet",
            name="students_count",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="Количество обучающихся"
            ),
            preserve_default=False,
        ),
    ]
